---
- name: Create directory for self-signed cert
  file:
    path: /etc/ssl/listmonk
    state: directory
    owner: root
    mode: "0755"

- name: Generate self-signed key & cert (valid 3 yrs)
  command: >
    openssl req -x509 -nodes -newkey rsa:2048
      -subj "/CN={{ listmonk_domain }}"
      -keyout /etc/ssl/listmonk/listmonk.key
      -out    /etc/ssl/listmonk/listmonk.crt
      -days   1095
  args:
    creates: /etc/ssl/listmonk/listmonk.crt

